version: "3.8"
services:
  rvc:
    image: rvcv2:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    container_name: rvc
    environment:
      - PORT=7801
    volumes:
      - ./weights:/app/weights
      - ./opt:/app/opt
      # - ./dataset:/app/dataset # you can use this folder in order to provide your dataset for model training
    ports:
      - 7801:7865
